name = "apps-api"
main = "index.js"  # da du im cf-worker/ Ordner bist
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "APPS_DATA"
id = "ee91aee19ba0422d85f8cd5c67e95970"

[[kv_namespaces]]
binding = "APPS_EDIT"
id = "586bee8e6587457086cb24524c0605e9"